// =============================================================================
// Unit tests for utils/digest.js — the digest composer + the SMTP client
// rewrite (Batch A audit fix A4).
//
// Coverage map:
//   - composeDigest: sections + title from fake counts (existing)
//   - composeDigest: filters zero-count sections (existing)
//   - _renderHtml: escapes user data (existing)
//   - _renderEml: produces a mime message (existing)
//   - sendDigest: persists + .eml fallback (existing)
//   - **NEW** _sendViaSmtp: greeting + EHLO + MAIL FROM + RCPT TO + DATA
//     + QUIT against a fake server that follows the protocol
//   - **NEW** _sendViaSmtp: rejects on a 5xx EHLO response
//   - **NEW** _sendViaSmtp: properly dot-stuffs a body line starting with `.`
//   - **NEW** _renderEml subject: encodes non-ASCII in a single RFC 2047
//     token (the prior version wrapped every non-ASCII byte in its own
//     token, producing malformed output)
// =============================================================================

'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const net = require('node:net');

const { composeDigest, sendDigest, _renderHtml, _renderEml } = require('./digest');
const { tick, _resetForTests } = require('../middleware/digestLoop');

// The SMTP rewrite lives in the digest module. We don't export it
// directly; we exercise it through _sendViaSmtp's behaviour by running
// it against an in-process net.Server that follows the RFC.

function makeFakePrisma(over = {}) {
  const counts = {
    testCase: { count: () => 1 },
    testRun: { count: () => 1 },
    ...over,
  };
  return {
    digestLog: {
      findFirst: async () => null,
      create: async ({ data }) => ({ id: 42, ...data }),
    },
    testCase: counts.testCase,
    testRun: counts.testRun,
  };
}

// ---- compose path (existing) ---------------------------------------------

test('composeDigest builds sections + title from fake counts', async () => {
  const db = makeFakePrisma({
    testCase: {
      count: async ({ where }) =>
        where.created_at && where.created_at.gte ? 3 : where.updated_at ? 2 : 9,
    },
    testRun: {
      count: async ({ where }) => (where.status === 'failed' ? 1 : where.status === 'errored' ? 0 : 5),
    },
  });

  const d = await composeDigest(1, { prisma: db, recipients: ['qa@example.com'] });
  assert.equal(d.project_id, 1);
  assert.equal(d.title, 'Regress digest: 3 new cases, 5 runs');
  const keys = d.sections.map((s) => s.key);
  assert.ok(keys.includes('new_cases'));
  assert.ok(keys.includes('changed_cases'));
  assert.ok(keys.includes('failures'));
  assert.ok(!keys.includes('errors'), 'zero-count eras should be filtered');
  assert.deepEqual(d.recipients, ['qa@example.com']);
  assert.ok(d.html.includes('Generated by Regress'));
});

test('composeDigest filters zero-count sections', async () => {
  const db = makeFakePrisma({
    testCase: { count: async () => 0 },
    testRun: { count: async () => 0 },
  });
  const d = await composeDigest(1, { prisma: db });
  assert.equal(d.sections.length, 0, 'quiet digest has no sections');
});

test('_renderHtml escapes user data', () => {
  const html = _renderHtml(
    [{ label: 'Total <runs>', count: 1 }],
    { title: 'Digest & stuff', windowStart: new Date('2026-01-01T00:00:00Z'), windowEnd: new Date('2026-01-01T00:00:00Z'), projectId: 1, liveCases: 1 },
  );
  assert.ok(html.includes('Total &lt;runs&gt;'), 'label should be escaped');
  assert.ok(html.includes('Digest &amp; stuff'), 'title should be escaped');
});

test('_renderEml produces a mime message with subject', () => {
  const digest = {
    title: 'Regress digest: 1 new case, 2 runs',
    recipients: ['qa@example.com'],
    html: '<html><body>hi</body></html>',
  };
  const eml = _renderEml(digest);
  assert.ok(eml.startsWith('From: Regress <no-reply@regress.local>'));
  assert.ok(eml.includes('\r\n\r\n'));
  assert.ok(eml.includes('To: qa@example.com'));
});

test('_renderEml encodes the entire subject in a single RFC 2047 token', () => {
  // Regression: the previous version of this file wrapped every non-ASCII
  // byte in its own `=?UTF-8?B??=` token, producing malformed output that
  // many MTAs bounced.
  const eml = _renderEml({ title: 'Café résumé — 5 cases', recipients: ['a@b.c'], html: 'x' });
  // Match exactly one subject line, with exactly one encoded word.
  const subjLine = eml.split('\r\n').find((l) => l.startsWith('Subject: '));
  const tokens = (subjLine.match(/\?=\s*\?=/g) || []).length;
  assert.equal(tokens, 0, 'subject must be a single RFC 2047 encoded word');
  // And the encoded form must decode back to the original (modulo CRLF).
  const m = subjLine.match(/^Subject: =\?UTF-8\?B\?(.+)\?=$/);
  assert.ok(m, `expected base64 RFC 2047 form, got: ${subjLine}`);
  assert.equal(Buffer.from(m[1], 'base64').toString('utf8'), 'Café résumé — 5 cases');
});

test('sendDigest persists a digest_log entry and returns log_id + delivery', async () => {
  const db = makeFakePrisma();
  const result = await sendDigest(1, { prisma: db });
  assert.equal(result.log_id, 42);
  assert.equal(result.delivery.delivered, false, 'falls back to file artifact w/o SMTP');
  assert.ok(result.delivery.artifact && path.isAbsolute(result.delivery.artifact));
  assert.ok(fs.existsSync(result.delivery.artifact));
  try {
    fs.rmSync(path.dirname(result.delivery.artifact), { recursive: true, force: true });
  } catch {}
});

// ---- digest loop (existing) ----------------------------------------------

test('digest loop respects DIGEST_ENABLED gating (any truthy value enables)', async () => {
  // Audit B1: the loop previously checked `process.env.DIGEST_ENABLED !== '1'`
  // which silently disabled the loop when an operator set `DIGEST_ENABLED=true`
  // (the canonical helper accepts any truthy value). Verify all common
  // truthy spellings now flip the loop on.
  const old = process.env.DIGEST_ENABLED;
  // Untouched env var → off.
  delete process.env.DIGEST_ENABLED;
  assert.equal(await tick({ prisma: makeFakePrisma() }), false);

  // 'true', 'yes', 'TRUE', '1' all enable.
  for (const v of ['true', 'TRUE', 'yes', '1']) {
    process.env.DIGEST_ENABLED = v;
    // Use a prisma that always reports the schedule is due AND that no
    // prior digest exists for this slot.
    const db = makeFakePrisma({
      digestLog: {
        findFirst: async () => null,
        create: async ({ data }) => ({ id: 99, ...data }),
      },
    });
    _resetForTests();
    const now = new Date(Date.now() + 2 * 60000);
    assert.equal(
      await tick({ prisma: db, now, dry: true }),
      true,
      `DIGEST_ENABLED=${v} must enable the loop`,
    );
  }

  // Explicitly false still disables.
  process.env.DIGEST_ENABLED = 'false';
  _resetForTests();
  assert.equal(
    await tick({ prisma: makeFakePrisma() }),
    false,
    'DIGEST_ENABLED=false must disable the loop',
  );

  if (old === undefined) delete process.env.DIGEST_ENABLED;
  else process.env.DIGEST_ENABLED = old;
});

test('digest loop does not re-fire when another instance owns the slot', async () => {
  // Audit B3: previously the loop relied solely on a module-local
  // `lastFiredKey` string, so two replicas could both decide "the slot
  // is mine" and double-send. Now the loop does a DB-level atomic
  // claim: if any digest_log row already has sent_at >= the next-fire
  // boundary, this replica defers to the other one.
  const oldEnabled = process.env.DIGEST_ENABLED;
  const oldSchedule = process.env.DIGEST_SCHEDULE;
  process.env.DIGEST_ENABLED = '1';
  process.env.DIGEST_SCHEDULE = '* * * * *';

  // Fake prisma that reports a row already exists for the slot.
  const db = {
    digestLog: {
      findFirst: async () => null, // for the initial `lastSentAt` lookup
      create: async ({ data }) => ({ id: 99, ...data }),
    },
    testCase: { count: async () => 0 },
    testRun: { count: async () => 0 },
  };

  // Patch digestLog.findFirst to return a "claimed" row on the second
  // call (the slot-claim check).
  let calls = 0;
  db.digestLog.findFirst = async () => {
    calls += 1;
    if (calls === 1) return null; // lastSentAt — no prior digest
    return { id: 7, sent_at: new Date(Date.now() + 60_000) }; // slot claimed
  };

  const now = new Date(Date.now() + 2 * 60000);
  _resetForTests();
  assert.equal(
    await tick({ prisma: db, now, dry: true }),
    false,
    'must defer to another instance that already owns the slot',
  );

  if (oldEnabled === undefined) delete process.env.DIGEST_ENABLED;
  else process.env.DIGEST_ENABLED = oldEnabled;
  if (oldSchedule === undefined) delete process.env.DIGEST_SCHEDULE;
  else process.env.DIGEST_SCHEDULE = oldSchedule;
});

test('digest loop fires when schedule + window pass', async () => {
  const oldEnabled = process.env.DIGEST_ENABLED;
  const oldSchedule = process.env.DIGEST_SCHEDULE;
  process.env.DIGEST_ENABLED = '1';
  process.env.DIGEST_SCHEDULE = '* * * * *';

  const db = makeFakePrisma();
  const now = new Date(Date.now() + 2 * 60000);
  _resetForTests();
  const sent = await tick({ prisma: db, now, dry: true });
  assert.equal(sent, true, 'should report a digest is due and fire');

  if (oldEnabled === undefined) delete process.env.DIGEST_ENABLED;
  else process.env.DIGEST_ENABLED = oldEnabled;
  if (oldSchedule === undefined) delete process.env.DIGEST_SCHEDULE;
  else process.env.DIGEST_SCHEDULE = oldSchedule;
});

test('digest loop does not re-fire for the same schedule slot', async () => {
  const oldEnabled = process.env.DIGEST_ENABLED;
  const oldSchedule = process.env.DIGEST_SCHEDULE;
  process.env.DIGEST_ENABLED = '1';
  process.env.DIGEST_SCHEDULE = '* * * * *';

  const db = makeFakePrisma();
  const now = new Date(Date.now() + 2 * 60000);
  _resetForTests();
  assert.equal(await tick({ prisma: db, now, dry: true }), true);
  assert.equal(
    await tick({ prisma: db, now, dry: true }),
    false,
    'same schedule slot must not double-send',
  );

  if (oldEnabled === undefined) delete process.env.DIGEST_ENABLED;
  else process.env.DIGEST_ENABLED = oldEnabled;
  if (oldSchedule === undefined) delete process.env.DIGEST_SCHEDULE;
  else process.env.DIGEST_SCHEDULE = oldSchedule;
});

// ---- SMTP client (Batch A audit fix A4) -----------------------------------

// Spin an in-process SMTP server that follows the protocol. The test
// can configure:
//   - `behavior.onCommand`: per-command hook to override responses (used
//     for the negative-path test that returns 5xx on EHLO).
//   - `received`: list of commands received, for assertions.
const startSmtpServer = (behavior = {}) => new Promise((resolve) => {
  const received = [];
  const server = net.createServer((sock) => {
    let buf = '';
    let inData = false;
    let dataBuf = '';
    sock.write('220 fake.test ESMTP ready\r\n');

    sock.on('data', (chunk) => {
      buf += chunk.toString('utf8');
      let nl;
      while ((nl = buf.indexOf('\r\n')) !== -1) {
        const line = buf.slice(0, nl);
        buf = buf.slice(nl + 2);
        if (inData) {
          if (line === '.') {
            inData = false;
            received.push({ cmd: 'DATA_BODY', body: dataBuf });
            dataBuf = '';
            const handler = (behavior.onCommand || {})['DATA_TERMINATOR'];
            sock.write(handler ? handler() : '250 OK message accepted\r\n');
          } else {
            // Reverse dot-stuffing for inspection.
            dataBuf += (line.startsWith('..') ? line.slice(1) : line) + '\r\n';
          }
          continue;
        }
        if (!line) continue;
        // Capture the command verb for assertions.
        const verb = line.split(' ')[0].toUpperCase();
        received.push({ cmd: verb, line });
        const handler = (behavior.onCommand || {})[verb];
        if (verb === 'DATA') {
          inData = true;
          sock.write(handler ? handler() : '354 End data with <CR><LF>.<CR><LF>\r\n');
          continue;
        }
        if (verb === 'QUIT') {
          sock.write(handler ? handler() : '221 Bye\r\n');
          sock.end();
          continue;
        }
        // Default success responses for the verbs we use.
        const defaults = {
          EHLO: () => '250-fake.test\r\n250-SIZE 10240000\r\n250 8BITMIME\r\n',
          HELO: () => '250 fake.test\r\n',
          STARTTLS: () => '454 TLS not available\r\n', // not enabled by default
          AUTH: () => '235 Authentication successful\r\n',
          'MAIL FROM': () => '250 OK\r\n',
          'RCPT TO': () => '250 OK\r\n',
        };
        const respond = handler || defaults[verb];
        sock.write(respond ? respond() : '250 OK\r\n');
      }
    });
    sock.on('error', () => {});
  });
  server.listen(0, '127.0.0.1', () => {
    const port = server.address().port;
    resolve({
      host: `127.0.0.1:${port}`,
      received,
      close: () => new Promise((r) => server.close(() => r())),
    });
  });
});

const makeDigest = () => ({
  title: 'Regress digest: 1 case, 2 runs',
  recipients: ['qa@example.com'],
  html: '<html><body>hi</body></html>',
  project_id: 1,
  window_start: new Date('2026-01-01T00:00:00Z'),
  window_end: new Date('2026-01-01T01:00:00Z'),
  sections: [{ key: 'new_cases', label: 'New cases', count: 1 }],
});

// Pull _sendViaSmtp out of the module via a side channel: since we don't
// export it, we trigger it through deliverDigest with SMTP_HOST set. To
// make that work without a DB we monkey-patch the module's senders.
const runSendViaSmtp = async (smtpHost, digest) => {
  // Reach the function via the deliverDigest path. We need a real DigestLog
  // row to come back; since we're testing the SMTP half, we can pass our
  // own log row.
  // The cleanest way: require the module, then call the inner function
  // through a back-door. Since we deliberately didn't export it, expose it
  // for tests by re-requiring with a side-channel flag.
  process.env.SMTP_HOST = smtpHost;
  const digestModule = require('./digest');
  // The function is module-scoped but reachable via deliverDigest's
  // internal branch. We replicate that branch's effect by reaching
  // through: re-export for the test only.
  if (!digestModule._sendViaSmtp) {
    throw new Error('digest module must export _sendViaSmtp for tests');
  }
  return digestModule._sendViaSmtp(digest, smtpHost);
};

test('_sendViaSmtp: completes EHLO → MAIL FROM → RCPT TO → DATA → QUIT', async () => {
  const srv = await startSmtpServer();
  try {
    const result = await runSendViaSmtp(srv.host, makeDigest());
    assert.equal(result.delivered, true, 'should report delivery success');

    const verbs = srv.received.map((r) => r.cmd);
    assert.equal(verbs[0], 'EHLO', 'first command after banner is EHLO');
    assert.ok(verbs.includes('MAIL'), 'must send MAIL FROM');
    assert.ok(verbs.includes('RCPT'), 'must send RCPT TO');
    assert.ok(verbs.includes('DATA'), 'must send DATA');
    assert.ok(verbs.includes('QUIT'), 'must send QUIT');
    // RCPT TO must come after MAIL FROM, and DATA must come after RCPT TO.
    const idxMail = verbs.indexOf('MAIL');
    const idxRcpt = verbs.indexOf('RCPT');
    const idxData = verbs.indexOf('DATA');
    assert.ok(idxMail < idxRcpt && idxRcpt < idxData, 'commands must be in RFC order');

    const body = srv.received.find((r) => r.cmd === 'DATA_BODY').body;
    assert.ok(body.includes('From: Regress <no-reply@regress.local>'));
    assert.ok(body.includes('To: qa@example.com'));
    assert.ok(body.includes('<html>'));
  } finally {
    delete process.env.SMTP_HOST;
    await srv.close();
  }
});

test('_sendViaSmtp: dot-stuffs body lines that start with a literal dot', async () => {
  // SMTP DATA requires every leading `.` to be doubled. The original
  // client never did this; if the digest body contained `.hidden` it
  // would be interpreted as the message terminator.
  const srv = await startSmtpServer();
  try {
    const digest = makeDigest();
    digest.html = '<html><body>.hidden line</body></html>';
    await runSendViaSmtp(srv.host, digest);
    const body = srv.received.find((r) => r.cmd === 'DATA_BODY').body;
    // The server side un-stuffs, so we should see the original `.hidden`
    // line (and not `..hidden`).
    assert.ok(body.includes('.hidden line'), 'body line should arrive un-stuffed at the server');
  } finally {
    delete process.env.SMTP_HOST;
    await srv.close();
  }
});

test('_sendViaSmtp: rejects when EHLO returns 5xx', async () => {
  const srv = await startSmtpServer({
    onCommand: {
      EHLO: () => '550 EHLO denied\r\n',
    },
  });
  try {
    const result = await runSendViaSmtp(srv.host, makeDigest());
    assert.equal(result.delivered, false, 'must not report delivery on EHLO failure');
    assert.ok(/EHLO/.test(result.error || ''), `error should mention EHLO, got: ${result.error}`);
    // MAIL FROM must NOT have been sent.
    const verbs = srv.received.map((r) => r.cmd);
    assert.ok(!verbs.includes('MAIL'), 'must not send MAIL FROM after EHLO failure');
  } finally {
    delete process.env.SMTP_HOST;
    await srv.close();
  }
});
