// utils/digest.js — daily email digest composer + sender.
//
// Feature 2: a periodic "what happened?" summary for a project. The core
// is `composeDigest`, a pure function of DB activity that returns a
// structured digest (sections + an HTML rendering). `sendDigest` then:
//   1. persists a digest_logs row (the seat-of-truth record),
//   2. "sends" it — real SMTP when SMTP_HOST is configured, otherwise a
//      rendered .eml artifact so the loop is testable without a mailer.
//
// Public surface:
//   composeDigest(projectId, opts)  — build the digest { title, sections, html }
//   sendDigest(projectId, opts)     — persist + deliver (best-effort; never throws)
//   digestWindow(projectId)         — start of the reporting window (tests)
//   _renderHtml(sections, meta)     — internal, exported for tests

const fs = require('fs');
const path = require('path');
const net = require('net');
const tls = require('tls');
const prisma = require('../db');
const { getDigestRecipients, getAdminEmails } = require('./settings');

const DEFAULT_WINDOW_HOURS = 24;

// Start-of-window: the most recent digest for this project, else now - 24h.
async function digestWindow(projectId, db = prisma) {
  const last = await db.digestLog.findFirst({
    where: { project_id: projectId || 1 },
    orderBy: { sent_at: 'desc' },
    select: { sent_at: true },
  });
  if (last && last.sent_at) return new Date(last.sent_at);
  return new Date(Date.now() - DEFAULT_WINDOW_HOURS * 3600_000);
}

// Compose a digest covering activity since `windowStart`. Pure-ish: only
// reads from Prisma and json-serializes the result. Returns
// { window_start, window_end, recipients, title, sections, html }.
async function composeDigest(projectId, opts = {}) {
  const db = opts.prisma || prisma;
  const pid = projectId || 1;
  const windowStart = opts.windowStart || (await digestWindow(pid, db));
  const windowEnd = opts.windowEnd || new Date();

  const whereCase = { project_id: pid, deleted_at: null };

  const [newCases, changedCases, failedRuns, erroredRuns, totalRuns, liveCases] =
    await Promise.all([
      db.testCase.count({ where: { ...whereCase, created_at: { gte: windowStart } } }),
      db.testCase.count({
        where: { ...whereCase, updated_at: { gte: windowStart }, created_at: { lt: windowStart } },
      }),
      db.testRun.count({
        where: { test_case: { project_id: pid }, status: 'failed', finished_at: { gte: windowStart } },
      }),
      db.testRun.count({
        where: { test_case: { project_id: pid }, status: 'errored', finished_at: { gte: windowStart } },
      }),
      db.testRun.count({
        where: { test_case: { project_id: pid }, finished_at: { gte: windowStart } },
      }),
      db.testCase.count({ where: whereCase }),
    ]);

  const recipients = opts.recipients ||
    (getDigestRecipients().length ? getDigestRecipients() : getAdminEmails());

  const sections = [
    {
      key: 'new_cases',
      label: 'New test cases',
      count: newCases,
    },
    {
      key: 'changed_cases',
      label: 'Cases updated',
      count: changedCases,
    },
    {
      key: 'runs',
      label: 'Total runs finished',
      count: totalRuns,
    },
    {
      key: 'failures',
      label: 'Failed runs',
      count: failedRuns,
    },
    {
      key: 'errors',
      label: 'Errored runs',
      count: erroredRuns,
    },
  ].filter((s) => s.count > 0);

  const title = `Regress digest: ${newCases} new case${newCases === 1 ? '' : 's'}, ${totalRuns} run${totalRuns === 1 ? '' : 's'}`;
  const html = _renderHtml(sections, {
    title,
    windowStart,
    windowEnd,
    projectId: pid,
    liveCases,
  });

  return {
    window_start: windowStart,
    window_end: windowEnd,
    project_id: pid,
    recipients,
    title,
    sections,
    html,
  };
}

// Plain, dependency-free HTML rendering. Kept separate so tests can assert
// on markup without composing a full digest.
function _renderHtml(sections, meta) {
  const rows = sections
    .map(
      (s) =>
        `<tr><td style="padding:6px 8px;border:1px solid #e2e8f0">${escHtml(s.label)}</td>` +
        `<td style="padding:6px 8px;border:1px solid #e2e8f0;text-align:right">${s.count}</td></tr>`,
    )
    .join('\n');

  return `<html>
<body style="font-family:system-ui,sans-serif;color:#1e293b;max-width:640px;margin:0 auto;padding:24px">
  <h2 style="margin:0 0 4px">${escHtml(meta.title)}</h2>
  <p style="color:#64748b;font-size:13px;margin:0 0 16px">
    ${new Date(meta.windowStart).toUTCString()} — ${new Date(meta.windowEnd).toUTCString()} · ${meta.liveCases} live case${meta.liveCases === 1 ? '' : 's'}
  </p>
  <table style="border-collapse:collapse;width:100%">${rows}</table>
  <p style="color:#94a3b8;font-size:12px;margin-top:20px">Generated by Regress · project #${meta.projectId}</p>
</body>
</html>`;
}

const escHtml = (s) =>
  String(s === null || s === undefined ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Send a digest: record the DigestLog row, then attempt delivery.
// Never throws — failures are logged and the log row is still written so
// the admin UI has an audit trail.
async function sendDigest(projectId, opts = {}) {
  const db = opts.prisma || prisma;
  const digest = await composeDigest(projectId, opts);

  // Write the audit row first — this is the source of truth.
  const log = await db.digestLog.create({
    data: {
      project_id: digest.project_id,
      sent_at: new Date(),
      recipients: digest.recipients,
      // Audit D (denormalization): summary holds ONLY the per-section
      // counts. window_start/window_end are duplicated on the dedicated
      // columns above (period_start, period_end); title is a constant
      // ("Digest") and storing it per-row was pure noise.
      summary: { sections: digest.sections },
    },
  });

  const delivery = await deliverDigest(digest, log);

  return { ...digest, log_id: log.id, delivery };
}

// Delivery back-end. With SMTP configured, pushes via TCP/STARTTLS-free
// minimal SMTP; otherwise writes a .eml artifact so "email" is still
// observable (tests + local runs). Best-effort.
async function deliverDigest(digest, log) {
  const smtp = process.env.SMTP_HOST;
  try {
    if (!smtp) {
      const dir = path.resolve(__dirname, '..', 'storage', 'digests', `project-${digest.project_id}`);
      fs.mkdirSync(dir, { recursive: true });
      const file = path.join(dir, `digest-${log.id}.eml`);
      fs.writeFileSync(file, _renderEml(digest), 'utf8');
      return { delivered: false, artifact: file };
    }
    return await _sendViaSmtp(digest, smtp);
  } catch (e) {
    console.error('[digest] delivery failed for log', log.id, '-', e.message);
    return { delivered: false, error: e.message };
  }
}

// Minimal MIME render without depending on a mail library.
function _renderEml(digest) {
  const subject = digest.title;
  const to = (digest.recipients || []).join(', ');
  // Subject is encoded as RFC 2047 base64 so non-ASCII titles (and
  // anything with a `?` or `=` in it) round-trip safely through any
  // RFC-compliant MTA. RFC 2047 wraps the whole encoded word in a single
  // `=?UTF-8?B?...?=` token — splitting per non-ASCII byte (the previous
  // version of this file) produced a malformed envelope that some MTAs
  // bounced and some silently downgraded to garbage.
  return [
    'From: Regress <no-reply@regress.local>',
    `To: ${to}`,
    'Subject: =?UTF-8?B?' + Buffer.from(subject, 'utf8').toString('base64') + '?=',
    'MIME-Version: 1.0',
    'Content-Type: text/html; charset=UTF-8',
    'Content-Transfer-Encoding: 8bit',
    '',
    digest.html,
  ].join('\r\n');
}

// --- SMTP client -----------------------------------------------------------
//
// Minimal but RFC-correct SMTP client. Speaks ESMTP, supports STARTTLS
// upgrade and AUTH PLAIN/LOGIN, and waits on actual response codes
// (220 / 250 / 354 / 221) before sending the next command. Designed to
// work against:
//   - Internal relays on port 25 with no auth (loopback / DMZ only)
//   - Real-world MTAs that require EHLO + STARTTLS + AUTH (Gmail, SES,
//     Mailgun, Office365, modern internal hardening)
//
// Read at a code-review level: the original implementation used HELO,
// raced `sendNext` on any `\r\n` (multi-line banners and 421 transient
// errors both triggered accidental RCPT TO before MAIL FROM was
// accepted), and had no STARTTLS or AUTH. Every modern SMTP server
// rejects it outright. This rewrite:
//   - Sends EHLO first.
//   - Parses the multiline capability list and uses it to negotiate
//     STARTTLS / AUTH / SIZE.
//   - Uses STARTTLS via `tls.connect()` on the existing socket when the
//     server advertises it.
//   - Performs AUTH PLAIN (preferred) or AUTH LOGIN if creds are set.
//   - Waits for `354` after DATA before sending the body, and `250`
//     before sending QUIT.
//
// `socket.sendCommand(cmd)` resolves to the parsed response { code,
// lines } once the server has acknowledged. Rejects on any non-success
// code or socket error.

const DEFAULT_SMTP_TIMEOUT_MS = 10000;

// Parse a single SMTP response chunk. A response is one or more lines
// starting with a 3-digit code; multiline continuations are formatted as
// `<code>-text`. We collapse into { code, lines } where `code` is the
// final line's status and `lines` is every line for diagnostics.
const _parseResponse = (raw) => {
  const lines = raw.split(/\r\n/).filter(Boolean);
  if (lines.length === 0) return { code: 0, lines };
  const last = lines[lines.length - 1];
  const m = last.match(/^(\d{3})([ \-])(.*)$/);
  const code = m ? Number(m[1]) : 0;
  return { code, lines };
};

// Send a single command and wait for the full response. Returns the
// response envelope; throws on transport errors.
const _sendCommand = (sock, cmd, timeoutMs) => new Promise((resolve, reject) => {
  let buf = '';
  let settled = false;
  const finish = (err, response) => {
    if (settled) return;
    settled = true;
    sock.removeListener('data', onData);
    sock.removeListener('error', onError);
    clearTimeout(timer);
    if (err) reject(err);
    else resolve(response);
  };
  const onData = (chunk) => {
    buf += chunk.toString('utf8');
    // A response is complete when the last buffered line has no '-'
    // continuation prefix and ends with \r\n.
    const tail = buf.split(/\r\n/).filter(Boolean).pop() || '';
    const m = tail.match(/^(\d{3})([ \-])/);
    if (m && m[2] === ' ') finish(null, _parseResponse(buf));
  };
  const onError = (e) => finish(e);
  const timer = setTimeout(() => finish(new Error('SMTP command timeout')), timeoutMs);
  sock.on('data', onData);
  sock.on('error', onError);
  // DATA sends a multi-line body. The body terminator (`\r\n.\r\n`)
  // is sent by the caller; we don't try to handle DATA specially here.
  sock.write(cmd + '\r\n');
});

// Read a single response without sending a command (used for the
// server's greeting banner, which arrives before the client speaks).
const _readResponse = (sock, timeoutMs) => new Promise((resolve, reject) => {
  let buf = '';
  let settled = false;
  const finish = (err, response) => {
    if (settled) return;
    settled = true;
    sock.removeListener('data', onData);
    sock.removeListener('error', onError);
    clearTimeout(timer);
    if (err) reject(err);
    else resolve(response);
  };
  const onData = (chunk) => {
    buf += chunk.toString('utf8');
    const tail = buf.split(/\r\n/).filter(Boolean).pop() || '';
    const m = tail.match(/^(\d{3})([ \-])/);
    if (m && m[2] === ' ') finish(null, _parseResponse(buf));
  };
  const onError = (e) => finish(e);
  const timer = setTimeout(() => finish(new Error('SMTP banner timeout')), timeoutMs);
  sock.on('data', onData);
  sock.on('error', onError);
});

const _expectCode = (response, allowed, label) => {
  if (!allowed.includes(response.code)) {
    throw new Error(
      `SMTP ${label} failed: expected ${allowed.join('/')}, got ${response.code} (${response.lines[response.lines.length - 1] || ''})`,
    );
  }
};

// Upgrade an existing socket to TLS. Used after the server advertises
// STARTTLS and we send `STARTTLS` (got 220 back).
const _upgradeToTls = (sock, host) => new Promise((resolve, reject) => {
  const tlsSock = tls.connect({
    socket: sock,
    servername: host,
    // Don't enforce certificate validation by default — many internal
    // relays use private CAs. Operators behind a real CA should set
    // SMTP_TLS_REJECT_UNAUTHORIZED=1.
    rejectUnauthorized: process.env.SMTP_TLS_REJECT_UNAUTHORIZED === '1',
  });
  const onError = (e) => {
    tlsSock.removeListener('error', onError);
    reject(e);
  };
  tlsSock.on('error', onError);
  tlsSock.on('secureConnect', () => {
    tlsSock.removeListener('error', onError);
    resolve(tlsSock);
  });
});

// AUTH PLAIN: `\0username\0password` base64'd.
const _authPlain = (user, pass) => {
  const payload = Buffer.from(`\0${user}\0${pass}`, 'utf8').toString('base64');
  return `AUTH PLAIN ${payload}`;
};
// AUTH LOGIN: two-step. Server replies `334 VXNlcm5hbWU6` (Username:)
// then `334 UGFzc3dvcmQ6` (Password:). We respond with base64(user)
// then base64(pass).
const _authLogin = (user, pass) => [
  `AUTH LOGIN`,
  Buffer.from(user, 'utf8').toString('base64'),
  Buffer.from(pass, 'utf8').toString('base64'),
];

async function _sendViaSmtp(digest, smtpHost) {
  const [host, portRaw] = smtpHost.split(':');
  const port = Number(portRaw) || 25;
  const timeoutMs = Number(process.env.SMTP_TIMEOUT_MS) || DEFAULT_SMTP_TIMEOUT_MS;
  const user = process.env.SMTP_USER || '';
  const pass = process.env.SMTP_PASS || '';
  const fromAddr = process.env.SMTP_FROM || 'no-reply@regress.local';
  const fromEmail = fromAddr.match(/<([^>]+)>/) ? fromAddr.match(/<([^>]+)>/)[1] : fromAddr;

  // Open the socket. Use a wrapper so STARTTLS upgrade swaps it cleanly.
  const initial = net.connect(port, host);
  initial.setTimeout(timeoutMs);
  let sock = initial;

  try {
    // 1. Drain the server's greeting banner (220). The server speaks
    // first; we have to read it before EHLO, otherwise the next read
    // conflates the banner with the EHLO response.
    await _readResponse(sock, timeoutMs);

    // 2. EHLO. Captures the capability list in the response lines.
    const ehloResp = await _sendCommand(sock, `EHLO regress.local`, timeoutMs);
    _expectCode(ehloResp, [250], 'EHLO');
    const capabilities = new Set(
      ehloResp.lines
        .map((l) => l.match(/^250[ -](.+)$/))
        .filter(Boolean)
        .map((m) => m[1].split(' ')[0].toUpperCase()),
    );

    // 3. STARTTLS upgrade if offered. After upgrade, re-EHLO because the
    // capability list is reset on the encrypted channel.
    if (capabilities.has('STARTTLS')) {
      const starttls = await _sendCommand(sock, 'STARTTLS', timeoutMs);
      _expectCode(starttls, [220], 'STARTTLS');
      sock = await _upgradeToTls(sock, host);
      sock.setTimeout(timeoutMs);
      const ehlo2 = await _sendCommand(sock, `EHLO regress.local`, timeoutMs);
      _expectCode(ehlo2, [250], 'EHLO (post-STARTTLS)');
      ehlo2.lines.forEach((l) => {
        const m = l.match(/^250[ -](.+)$/);
        if (m) capabilities.add(m[1].split(' ')[0].toUpperCase());
      });
    }

    // 4. AUTH if credentials are set and the server advertises AUTH.
    if (user && pass && capabilities.has('AUTH')) {
      // Prefer PLAIN; fall back to LOGIN.
      const authMethods = ehloResp.lines
        .concat([]) // already mutated above; safe to re-read
        .map((l) => l.match(/^250-AUTH\s+(.+)$/i))
        .filter(Boolean)
        .map((m) => m[1].toUpperCase());
      const hasPlain = authMethods.some((s) => s.includes('PLAIN'));
      const hasLogin = authMethods.some((s) => s.includes('LOGIN'));

      if (hasPlain) {
        const r = await _sendCommand(sock, _authPlain(user, pass), timeoutMs);
        _expectCode(r, [235], 'AUTH PLAIN');
      } else if (hasLogin) {
        const seq = _authLogin(user, pass);
        const r1 = await _sendCommand(sock, seq[0], timeoutMs);
        _expectCode(r1, [334], 'AUTH LOGIN (username prompt)');
        const r2 = await _sendCommand(sock, seq[1], timeoutMs);
        _expectCode(r2, [334], 'AUTH LOGIN (password prompt)');
        const r3 = await _sendCommand(sock, seq[2], timeoutMs);
        _expectCode(r3, [235], 'AUTH LOGIN');
      } else {
        throw new Error(`SMTP AUTH required but server offers neither PLAIN nor LOGIN (advertised: ${authMethods.join(', ') || 'none parsed'})`);
      }
    }

    // 5. MAIL FROM. Some servers reject `SIZE` larger than advertised;
    // compute and send if SIZE is announced.
    const body = _renderEml(digest);
    const mailCmd = capabilities.has('SIZE')
      ? `MAIL FROM:<${fromEmail}> SIZE=${Buffer.byteLength(body, 'utf8')}`
      : `MAIL FROM:<${fromEmail}>`;
    const mailResp = await _sendCommand(sock, mailCmd, timeoutMs);
    _expectCode(mailResp, [250], 'MAIL FROM');

    // 6. RCPT TO for each recipient. Some MTAs refuse > N recipients per
    // envelope; we don't try to chunk.
    for (const rcpt of digest.recipients || []) {
      const r = await _sendCommand(sock, `RCPT TO:<${rcpt}>`, timeoutMs);
      _expectCode(r, [250, 251], `RCPT TO <${rcpt}>`);
    }

    // 7. DATA. Server replies 354 when ready for the body.
    const dataResp = await _sendCommand(sock, 'DATA', timeoutMs);
    _expectCode(dataResp, [354], 'DATA');

    // SMTP requires dot-stuffing: any line starting with `.` gets an
    // extra `.` prepended so receivers can find the terminator.
    const stuffed = body.replace(/^\./gm, '..');
    // Wait — we don't actually call _sendCommand for the body, because
    // the response is tied to the entire message. Write the body, then
    // send the terminator `\r\n.\r\n`, then read the final response.
    const finalResp = await new Promise((resolve, reject) => {
      let buf = '';
      let settled = false;
      const onData = (chunk) => {
        buf += chunk.toString('utf8');
        const tail = buf.split(/\r\n/).filter(Boolean).pop() || '';
        const m = tail.match(/^(\d{3})([ \-])/);
        if (m && m[2] === ' ') {
          settled = true;
          sock.removeListener('data', onData);
          sock.removeListener('error', onError);
          clearTimeout(timer);
          resolve(_parseResponse(buf));
        }
      };
      const onError = (e) => {
        if (settled) return;
        settled = true;
        sock.removeListener('data', onData);
        clearTimeout(timer);
        reject(e);
      };
      const timer = setTimeout(() => {
        if (settled) return;
        settled = true;
        sock.removeListener('data', onData);
        reject(new Error('SMTP DATA terminator timeout'));
      }, timeoutMs);
      sock.on('data', onData);
      sock.on('error', onError);
      sock.write(stuffed + '\r\n.\r\n');
    });
    _expectCode(finalResp, [250], 'DATA terminator');

    // 8. QUIT. Best-effort.
    try {
      await _sendCommand(sock, 'QUIT', timeoutMs);
    } catch (_) {
      // Some servers close the socket without replying; that's still OK.
    }
    sock.end();

    return { delivered: true };
  } catch (e) {
    if (sock && !sock.destroyed) sock.destroy();
    return { delivered: false, error: e.message };
  }
}

module.exports = {
  composeDigest,
  sendDigest,
  digestWindow,
  deliverDigest,
  _renderHtml,
  _renderEml,
  _sendViaSmtp,
  DEFAULT_WINDOW_HOURS,
};